version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - sejm

  app:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - sejm

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - app
    networks:
      - sejm

  frontend:
    build:
      context: ./frontend
      dockerfile: ../.docker/nextjs/Dockerfile
    volumes:
      - ./media:/app/public/media
      - ./frontend/app:/app/app
      - ./frontend/components:/app/components
      - ./frontend/public:/app/public
      - ./frontend/.env:/app/.env
      - ./frontend/.env.local:/app/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=https://sejm-stats.pl/api
    depends_on:
      - app
    networks:
      - sejm

  redis:
    image: redis:latest
    networks:
      - sejm

volumes:
  postgres_data:

networks:
  sejm:
    driver: bridge
