version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    env_file:
      - .env
    networks:
      - sejm

  app:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
      target: ${BUILD_TARGET:-dev}
    volumes:
      - ./src:/code
    # - ./src/manage.py:/code/manage.py
    ports:
      - ${EXTERNAL_NGINX_PORT:-80}:80
    env_file:
      - .env
    networks:
      - sejm
  frontend:
    build:
      context: ./frontend
      dockerfile: ../.docker/nextjs/Dockerfile
    volumes:
      - ./media:/app/public/media # Mount media directory
      - ./frontend/app:/app/app # Mount only the app directory
      - ./frontend/components:/app/components # Mount components
      - ./frontend/public:/app/public # Mount public directory
      - ./frontend/.env:/app/.env # Mount .env file
      - ./frontend/.env.local:/app/.env.local # Mount .env.local file
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://app # Set the API URL to the app service
    depends_on:
      - app
    networks:
      - sejm

  redis:
    image: redis:latest
    networks:
      - sejm
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - sejm

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email michalskibinski109@gmail.com -d sejm-stats.pl --agree-tos

volumes:
  postgres_data:

networks:
  sejm:
    driver: bridge
