version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    env_file:
      - .env
    networks:
      - sejm

  app:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
      target: ${BUILD_TARGET:-dev}
    volumes:
      - ./src:/code
    # - ./src/manage.py:/code/manage.py
    ports:
      - ${EXTERNAL_NGINX_PORT:-80}:80
    env_file:
      - .env
    networks:
      - sejm
  frontend:
    build:
      context: ./frontend
      dockerfile: ../.docker/nextjs/Dockerfile
    volumes:
      - ./frontend:/app
      - ./media:/app/public/media # Mount media directory
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://app # Set the API URL to the app service
    env_file:
      - ./frontend/.env
    depends_on:
      - app
    networks:
      - sejm

  redis:
    image: redis:latest
    networks:
      - sejm

volumes:
  postgres_data:

networks:
  sejm:
    driver: bridge
